/*
 * Team             |   Chandler
 * Members          |   Braden Fiedel, Caden Erickson, Connor Blood, Josie Fiedel
 * Class            |   CS 3505
 * Project          |   A8: Sprint 2
 * Last modified    |   April 26, 2023
 *
 * This file contains the class definition for the MainMenu class.
 */


#ifndef MAINMENU_H
#define MAINMENU_H

#include <QWidget>


QT_BEGIN_NAMESPACE
namespace Ui { class MainMenu; }
QT_END_NAMESPACE

/**
 * @brief The MainMenu class
 * This class represents the main splash screen of the program, and emits
 * appropriate signals for the events generated by clicks on any of the three
 * buttons.
 */
class MainMenu : public QWidget
{
    Q_OBJECT

public:
    explicit MainMenu(QWidget* parent = nullptr);
    ~MainMenu();

private:
    Ui::MainMenu* ui;

signals:
    void buttonPressed(int);
    void exitPressed();
};

#endif // MAINMENU_H
